import type { Config } from "tailwindcss";

export default {
  content: ["./{pages,layouts,components,src}/**/*.{html,js,jsx,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        pokemon: {
          normal: "#A8A77A",
          fire: "#EE8130",
          water: "#6390F0",
          electric: "#F7D02C",
          grass: "#7AC74C",
          ice: "#96D9D6",
          fighting: "#C22E28",
          poison: "#A33EA1",
          ground: "#E2BF65",
          flying: "#A98FF3",
          psychic: "#F95587",
          bug: "#A6B91A",
          rock: "#B6A136",
          ghost: "#735797",
          dragon: "#6F35FC",
          dark: "#705746",
          steel: "#B7B7CE",
          fairy: "#D685AD",
        },
      },
    },
  },
  plugins: [],
  safelist: [
    "bg-gray-400",
    "bg-orange-500",
    "bg-blue-500",
    "bg-yellow-400",
    "bg-green-500",
    "bg-cyan-300",
    "bg-red-600",
    "bg-purple-500",
    "bg-yellow-600",
    "bg-indigo-400",
    "bg-pink-500",
    "bg-lime-500",
    "bg-yellow-700",
    "bg-purple-700",
    "bg-indigo-600",
    "bg-gray-700",
    "bg-gray-500",
    "bg-pink-400",
    "bg-pokemon-normal",
    "bg-pokemon-fire",
    "bg-pokemon-water",
    "bg-pokemon-electric",
    "bg-pokemon-grass",
    "bg-pokemon-ice",
    "bg-pokemon-fighting",
    "bg-pokemon-poison",
    "bg-pokemon-ground",
    "bg-pokemon-flying",
    "bg-pokemon-psychic",
    "bg-pokemon-bug",
    "bg-pokemon-rock",
    "bg-pokemon-ghost",
    "bg-pokemon-dragon",
    "bg-pokemon-dark",
    "bg-pokemon-steel",
    "bg-pokemon-fairy",
  ],
} satisfies Config;
